[package]
name = "kprober"
version = "0.1.0"
authors = ["hwipl"]
edition = "2021"

# See more keys and their definitions at
# https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = "0.21.1"
clap = "4.5.23"
ctrlc = "3.4.5"
