[package]
name = "kprober"
version = "0.1.0"
authors = ["hwipl"]
edition = "2021"

# See more keys and their definitions at
# https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = "0.20.0"
clap = "4.4.3"
ctrlc = "3.4.1"
